security:
    firewalls:
        main:
            pattern:   ^/admin
            anonymous: true
            provider:  in_memory
            form_login:
                login_path: admin/login
                check_path: login_check
            logout:
                path:   logout
                target: /platform
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    providers:
        in_memory:
            memory:
               users:
                    ryan:
                          password: ryanpass
                          roles: 'ROLE_USER'
                    admin:
                         password: kitten
                         roles: 'ROLE_ADMIN'


    encoders:
        Symfony\Component\Security\Core\User\User: plaintext