<?php

namespace MIRE\AdminBundle\Repository;

/**
 * AbonemtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonemtRepository extends \Doctrine\ORM\EntityRepository
{
}
