<?php

namespace MIRE\AdminBundle\Repository;
use MIRE\AdminBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategorie($categorie_id)
    {
        $query  = $this->_em->createQuery('SELECT a FROM MIRE\AdminBundle\Entity\Article a JOIN a.categories c WHERE c.id = :id ORDER BY a.id ' );
        $query->setParameter('id',$categorie_id);
        return $query->setMaxResults(3)->getResult();
    }
    public function findByCategorieLast($categorie_id)
    {
        $query  = $this->_em->createQuery('SELECT a FROM MIRE\AdminBundle\Entity\Article a JOIN a.categories c WHERE c.id = :id ORDER BY a.id DESC');
        $query->setParameter('id',$categorie_id);
        return $query->setMaxResults(1)->getSingleResult();
    }

    public function findByPlace($place_num)
    {
        $query  = $this->_em->createQuery('SELECT a FROM MIRE\AdminBundle\Entity\Article a JOIN a.categories c WHERE c.place = :place  ORDER BY a.id DESC');
        $query->setParameter('place',$place_num);
        return $query->setMaxResults(3)->getResult();
    }
    public function findByPlaceLast($place_num)
    {
        $query  = $this->_em->createQuery('SELECT a FROM MIRE\AdminBundle\Entity\Article a JOIN a.categories c WHERE c.place = :place  ORDER BY a.id DESC');
        $query->setParameter('place',$place_num);
        return $query->setMaxResults(1)->getSingleResult();
    }

    public function testCode()
    {
        $query  = $this->_em->createQuery('SELECT a FROM MIRE\AdminBundle\Entity\Article a');
        return $query->getResult();
    }
}
